--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/19/2022 2:21:33 AM
-- Server version: 8.0.30
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE quan_ly_website_ban_dien_thoai;

--
-- Drop table `promotioncategory`
--
DROP TABLE IF EXISTS promotioncategory;

--
-- Drop table `promotion`
--
DROP TABLE IF EXISTS promotion;

--
-- Drop table `orderdetail`
--
DROP TABLE IF EXISTS orderdetail;

--
-- Drop table `order`
--
DROP TABLE IF EXISTS `order`;

--
-- Drop table `orderstatus`
--
DROP TABLE IF EXISTS orderstatus;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `role`
--
DROP TABLE IF EXISTS role;

--
-- Drop table `productconfiguration`
--
DROP TABLE IF EXISTS productconfiguration;

--
-- Drop table `productitem`
--
DROP TABLE IF EXISTS productitem;

--
-- Drop table `product`
--
DROP TABLE IF EXISTS product;

--
-- Drop table `brand`
--
DROP TABLE IF EXISTS brand;

--
-- Drop table `variationoption`
--
DROP TABLE IF EXISTS variationoption;

--
-- Drop table `variation`
--
DROP TABLE IF EXISTS variation;

--
-- Drop table `productcategory`
--
DROP TABLE IF EXISTS productcategory;

--
-- Set default database
--
USE quan_ly_website_ban_dien_thoai;

--
-- Create table `productcategory`
--
CREATE TABLE productcategory (
  ProductCategoryID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  SubProductCategoryID int DEFAULT NULL COMMENT 'Loại sản phẩm con (Khóa ngoại)',
  ProductCategoryName varchar(255) DEFAULT NULL COMMENT 'Tên loại sản phẩm',
  PRIMARY KEY (ProductCategoryID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng loại sản phẩm';

--
-- Create foreign key
--
ALTER TABLE productcategory
ADD CONSTRAINT FK_productcategory_productcategory_ProductCategoryID FOREIGN KEY (SubProductCategoryID)
REFERENCES productcategory (ProductCategoryID);

--
-- Create table `variation`
--
CREATE TABLE variation (
  VariationID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  ProductCategoryID int DEFAULT NULL COMMENT 'Loại sản phẩm (Khóa ngoại)',
  VariationName varchar(255) DEFAULT NULL COMMENT 'Tên loại đặc trưng',
  PRIMARY KEY (VariationID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng loại đặc trưng';

--
-- Create foreign key
--
ALTER TABLE variation
ADD CONSTRAINT FK_variation_productcategory_ProductCategoryID FOREIGN KEY (ProductCategoryID)
REFERENCES productcategory (ProductCategoryID);

--
-- Create table `variationoption`
--
CREATE TABLE variationoption (
  VariationOptionID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  VariationID int DEFAULT NULL COMMENT 'Loại đặc trưng (Khóa ngoại)',
  Value varchar(255) DEFAULT NULL COMMENT 'Giá trị',
  PRIMARY KEY (VariationOptionID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng đặc trưng';

--
-- Create foreign key
--
ALTER TABLE variationoption
ADD CONSTRAINT FK_variationoption_variation_VariationID FOREIGN KEY (VariationID)
REFERENCES variation (VariationID);

--
-- Create table `brand`
--
CREATE TABLE brand (
  BrandID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  SubBrandID int DEFAULT NULL COMMENT 'Thương hiệu con (Khóa ngoại)',
  BrandName varchar(255) DEFAULT NULL COMMENT 'Tên thương hiệu',
  PRIMARY KEY (BrandID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng thương hiệu';

--
-- Create foreign key
--
ALTER TABLE brand
ADD CONSTRAINT FK_brand_brand_BrandID FOREIGN KEY (SubBrandID)
REFERENCES brand (BrandID);

--
-- Create table `product`
--
CREATE TABLE product (
  ProductID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  ProductCode varchar(255) DEFAULT NULL COMMENT 'Mã sản phẩm',
  ProductName varchar(255) DEFAULT NULL COMMENT 'Tên sản phẩm',
  ProductCategoryID int DEFAULT NULL COMMENT 'Loại sản phẩm (Khóa ngoại)',
  BrandID int DEFAULT NULL COMMENT 'Thương hiệu (Khóa ngoại)',
  ProductDescription text DEFAULT NULL COMMENT 'Mô tả',
  Image varchar(255) DEFAULT NULL COMMENT 'Hình ảnh',
  PRIMARY KEY (ProductID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng sản phẩm';

--
-- Create foreign key
--
ALTER TABLE product
ADD CONSTRAINT FK_product_brand_BrandID FOREIGN KEY (BrandID)
REFERENCES brand (BrandID);

--
-- Create foreign key
--
ALTER TABLE product
ADD CONSTRAINT FK_product_productcategory_ProductCategoryID FOREIGN KEY (ProductCategoryID)
REFERENCES productcategory (ProductCategoryID);

--
-- Create table `productitem`
--
CREATE TABLE productitem (
  ProductItemID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  ProductID int DEFAULT NULL COMMENT 'Sản phẩm (Khóa ngoại)',
  SKU varchar(255) DEFAULT NULL COMMENT 'Số định danh xác định cho từng sản phẩm (VD: IMEI)',
  Amount int DEFAULT NULL COMMENT 'Số lượng',
  Price float DEFAULT NULL COMMENT 'Giá bán',
  Image varchar(255) DEFAULT NULL COMMENT 'Hình ảnh',
  PRIMARY KEY (ProductItemID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng chi tiết sản phẩm';

--
-- Create foreign key
--
ALTER TABLE productitem
ADD CONSTRAINT FK_productitem_product_ProductID FOREIGN KEY (ProductID)
REFERENCES product (ProductID);

--
-- Create table `productconfiguration`
--
CREATE TABLE productconfiguration (
  ProductItemID int NOT NULL COMMENT 'Khóa chính',
  VariationOptionID int NOT NULL COMMENT 'Khóa chính'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng trung gian giữa chi tiết sản phẩm và các đặc trưng sản phẩm';

--
-- Create foreign key
--
ALTER TABLE productconfiguration
ADD CONSTRAINT FK_productconfiguration_productitem_ProductItemID FOREIGN KEY (ProductItemID)
REFERENCES productitem (ProductItemID);

--
-- Create foreign key
--
ALTER TABLE productconfiguration
ADD CONSTRAINT FK_productconfiguration_variationoption_VariationOptionID FOREIGN KEY (VariationOptionID)
REFERENCES variationoption (VariationOptionID);

--
-- Create table `role`
--
CREATE TABLE role (
  RoleID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  RoleName varchar(255) DEFAULT NULL COMMENT 'Tên vai trò',
  PRIMARY KEY (RoleID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng vai trò người dùng';

--
-- Create table `user`
--
CREATE TABLE user (
  UserID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  UserAccount varchar(255) DEFAULT NULL COMMENT 'Tài khoản người dùng',
  Password varchar(255) DEFAULT NULL COMMENT 'Mật khẩu',
  UserName varchar(255) DEFAULT NULL COMMENT 'Tên người dùng',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ',
  Email varchar(255) DEFAULT NULL COMMENT 'Email',
  PhoneNumber varchar(20) DEFAULT NULL COMMENT 'Số điện thoại',
  Image text DEFAULT NULL COMMENT 'Hình ảnh avatar',
  RoleID int DEFAULT NULL COMMENT 'Vai trò người dùng (Khóa ngoại)',
  PRIMARY KEY (UserID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng người dùng';

--
-- Create foreign key
--
ALTER TABLE user
ADD CONSTRAINT FK_user_role_RoleID FOREIGN KEY (RoleID)
REFERENCES role (RoleID);

--
-- Create table `orderstatus`
--
CREATE TABLE orderstatus (
  OrderStatusID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  OrderStatus varchar(255) DEFAULT NULL COMMENT 'Trạng thái đơn đặt',
  PRIMARY KEY (OrderStatusID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng trạng thái đơn đặt';

--
-- Create table `order`
--
CREATE TABLE `order` (
  OrderID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  UserID int DEFAULT NULL COMMENT 'Người đặt (Khóa ngoại)',
  OrderDate datetime DEFAULT NULL COMMENT 'Thời gian đặt',
  TotalAmount float DEFAULT NULL COMMENT 'Tổng tiền',
  OrderStatusID int DEFAULT NULL COMMENT 'Trạng thái (Khóa ngoại)',
  PRIMARY KEY (OrderID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng đơn đặt hàng';

--
-- Create foreign key
--
ALTER TABLE `order`
ADD CONSTRAINT FK_order_orderstatus_OrderStatusID FOREIGN KEY (OrderStatusID)
REFERENCES orderstatus (OrderStatusID);

--
-- Create foreign key
--
ALTER TABLE `order`
ADD CONSTRAINT FK_order_user_UserID FOREIGN KEY (UserID)
REFERENCES user (UserID);

--
-- Create table `orderdetail`
--
CREATE TABLE orderdetail (
  OderID int DEFAULT NULL,
  ProductItemID int DEFAULT NULL,
  Amount int DEFAULT NULL COMMENT 'Số lượng',
  Price float DEFAULT NULL COMMENT 'Thành tiền'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng chi tiết đơn đặt';

--
-- Create foreign key
--
ALTER TABLE orderdetail
ADD CONSTRAINT FK_orderdetail_order_OrderID FOREIGN KEY (OderID)
REFERENCES `order` (OrderID);

--
-- Create foreign key
--
ALTER TABLE orderdetail
ADD CONSTRAINT FK_orderdetail_productitem_ProductItemID FOREIGN KEY (ProductItemID)
REFERENCES productitem (ProductItemID);

--
-- Create table `promotion`
--
CREATE TABLE promotion (
  PromotionID int NOT NULL AUTO_INCREMENT COMMENT 'Khóa chính',
  PromotionName varchar(255) DEFAULT NULL COMMENT 'Tên khuyến mại',
  Description varchar(255) DEFAULT NULL COMMENT 'Mô tả',
  DiscountRate float DEFAULT NULL COMMENT 'Phần trăm giảm giá',
  StartDate datetime DEFAULT NULL COMMENT 'Thời gian bắt đầu',
  EndDate datetime DEFAULT NULL COMMENT 'Thời gian kết thúc',
  PRIMARY KEY (PromotionID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng khuyến mại';

--
-- Create table `promotioncategory`
--
CREATE TABLE promotioncategory (
  PromotionID int DEFAULT NULL,
  ProductCategoryID int DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Bảng trung gian giữa bảng khuyến mại và loại sản phẩm';

--
-- Create foreign key
--
ALTER TABLE promotioncategory
ADD CONSTRAINT FK_promotioncategory_productcategory_ProductCategoryID FOREIGN KEY (ProductCategoryID)
REFERENCES productcategory (ProductCategoryID);

--
-- Create foreign key
--
ALTER TABLE promotioncategory
ADD CONSTRAINT FK_promotioncategory_promotion_PromotionID FOREIGN KEY (PromotionID)
REFERENCES promotion (PromotionID);

-- 
-- Dumping data for table productcategory
--
-- Table quan_ly_website_ban_dien_thoai.productcategory does not contain any data (it is empty)

-- 
-- Dumping data for table brand
--
-- Table quan_ly_website_ban_dien_thoai.brand does not contain any data (it is empty)

-- 
-- Dumping data for table role
--
-- Table quan_ly_website_ban_dien_thoai.role does not contain any data (it is empty)

-- 
-- Dumping data for table variation
--
-- Table quan_ly_website_ban_dien_thoai.variation does not contain any data (it is empty)

-- 
-- Dumping data for table product
--
-- Table quan_ly_website_ban_dien_thoai.product does not contain any data (it is empty)

-- 
-- Dumping data for table user
--
-- Table quan_ly_website_ban_dien_thoai.user does not contain any data (it is empty)

-- 
-- Dumping data for table orderstatus
--
-- Table quan_ly_website_ban_dien_thoai.orderstatus does not contain any data (it is empty)

-- 
-- Dumping data for table promotion
--
-- Table quan_ly_website_ban_dien_thoai.promotion does not contain any data (it is empty)

-- 
-- Dumping data for table variationoption
--
-- Table quan_ly_website_ban_dien_thoai.variationoption does not contain any data (it is empty)

-- 
-- Dumping data for table productitem
--
-- Table quan_ly_website_ban_dien_thoai.productitem does not contain any data (it is empty)

-- 
-- Dumping data for table `order`
--
-- Table quan_ly_website_ban_dien_thoai.`order` does not contain any data (it is empty)

-- 
-- Dumping data for table promotioncategory
--
-- Table quan_ly_website_ban_dien_thoai.promotioncategory does not contain any data (it is empty)

-- 
-- Dumping data for table productconfiguration
--
-- Table quan_ly_website_ban_dien_thoai.productconfiguration does not contain any data (it is empty)

-- 
-- Dumping data for table orderdetail
--
-- Table quan_ly_website_ban_dien_thoai.orderdetail does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;